name: diabetty
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^0.1.3
  simple_animations: ^1.3.3
  google_fonts:
  
  cloud_firestore: ^0.12.9+4
  firebase_analytics: ^5.0.2
  firebase_core:
  firebase_storage:
  intl:
  firebase_auth: ^0.15.3
  google_sign_in: ^4.1.1
  #flutter_facebook_login: ^3.0.0
  apple_sign_in: ^0.1.0
  provider: ^4.0.1
  firebase_dynamic_links:
    git:
      url: https://github.com/mrmilu/flutterfire
      path: packages/firebase_dynamic_links
      ref: firebase_dynamic_links
  rxdart: ^0.23.1
  flutter_secure_storage: ^3.3.1+1
  package_info: ^0.4.0+13
  random_string: ^2.0.0
  flutter_svg: ^0.19.0
  validators: ^2.0.1
  focused_menu: ^1.0.0
  nb_utils: ^3.1.6+11
  
  flutter_statusbarcolor: 0.2.3
  flutter_slidable:
  flutter_staggered_grid_view:
  date_picker_timeline: 1.2.1
  circle_list: ^1.0.2
  date_range_picker: ^1.0.6
  animator: ^2.0.1
  weekday_selector: ^0.4.0
  like_button: ^1.0.3
  duration: 2.0.15
  circular_check_box: ^1.0.4
  marquee: ^1.6.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/2.0x/
    - assets/3.0x/
    - assets/icons/social/
    - assets/icons/navigation/gradient-icons/
    - assets/icons/navigation/gradient-icons/svg/
    - assets/icons/navigation/checkbox/
    - assets/icons/navigation/clock/
    - assets/icons/navigation/essentials/
    - assets/icons/navigation/more/
    - assets/icons/navigation/other/
    - assets/icons/navigation/x/

fonts:
- family: Neue-Book
  fonts:
    - assets/fonts/frutiger-neue-It-cufonfonts/Frutiger-Neue-LT-Book.ttf
- family: Neue-Lt
  fonts:
    - assets/fonts/frutiger-neue-It-cufonfonts/Frutiger-Neue-LT.ttf
- family: Heletica-Font
  fonts:
    - assets/fonts/Helvetica-Font/Helvetica.ttf
- family: Heletica-Bold
  fonts:
    - assets/fonts/Helvetica-Font/Helvetica-Bold.ttf
- family: Futura
  fonts:
    - assets/fonts/futura-book-bt-22240.ttf
- family: Nimbus
  fonts:
    - assets/fonts/Nimbus-Sans.ttf
  
  
  

  