name: diabetty
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_clock_helper:
    git:
      url: git://github.com/flutter/flutter_clock.git
      path: flutter_clock_helper
  cupertino_icons: ^0.1.3
  simple_animations: ^1.3.3
  google_fonts:
  intl:
  provider: ^4.0.1
  app_settings: ^4.1.1
  share: ^2.0.4
  launch_review: ^3.0.1
  url_launcher: ^6.0.12


  rxdart: ^0.23.1
  flutter_secure_storage: ^3.3.1+1
  package_info: ^0.4.0+13
  random_string: ^2.0.0
  flutter_svg: ^0.20.0-nullsafety.3
  validators: ^2.0.1
  focused_menu: ^1.0.0
  nb_utils: ^3.1.6+11
  flutter_slidable:
  flutter_staggered_grid_view:
  date_picker_timeline: 1.2.1
  circle_list: ^1.0.2
  date_range_picker: ^1.0.7
  animator: ^2.0.1
  weekday_selector: ^0.4.0
  like_button: ^1.0.3
  duration: 2.0.15
  circular_check_box: ^1.0.4
  marquee: ^1.6.1
  fcharts: ^0.0.11
  fl_chart: ^0.35.0
  modern_charts: ^0.1.19
  syncfusion_flutter_charts: ^18.3.48+1
  animated_button: ^0.1.2
  calendar_strip: ^1.0.6
  intl_phone_number_input: ^0.7.0+1
  flutter_local_notifications: ^5.0.0+3
  localstore: ^1.2.0
  flutter_native_timezone: ^2.0.0
  device_info: ^2.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/2.0x/
    - assets/3.0x/
    - assets/icons/social/
    - assets/icons/navigation/gradient-icons/
    - assets/icons/navigation/gradient-icons/svg/
    - assets/icons/navigation/checkbox/
    - assets/icons/navigation/clock/
    - assets/icons/navigation/essentials/
    - assets/icons/navigation/more/
    - assets/icons/navigation/other/
    - assets/icons/navigation/x/
    - assets/icons/infob/
    - assets/icons/moreb/
    - assets/images/
    - assets/images/empty_team.svg
    

fonts:
  - family: Neue-Book
    fonts:
      - assets/fonts/frutiger-neue-It-cufonfonts/Frutiger-Neue-LT-Book.ttf
  - family: Neue-Lt
    fonts:
      - assets/fonts/frutiger-neue-It-cufonfonts/Frutiger-Neue-LT.ttf
  - family: Heletica-Font
    fonts:
      - assets/fonts/Helvetica-Font/Helvetica.ttf
  - family: Heletica-Bold
    fonts:
      - assets/fonts/Helvetica-Font/Helvetica-Bold.ttf
  - family: Futura
    fonts:
      - assets/fonts/futura-book-bt-22240.ttf
  - family: Nimbus
    fonts:
      - assets/fonts/Nimbus-Sans.ttf
